name: Build docker image

on:
  push:
    branches:
      - master
      - main

    tags:
      - '*'

env:
  RABBITMQ42: '4.2.5'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      rabbitmq-versions: ${{ steps.set-matrix.outputs.rabbitmq-versions }}
    steps:
      - id: set-matrix
        run: |
          cat << 'EOF' > versions.json
          [
            {"key": "rabbitmq42", "version": "${{ env.RABBITMQ42 }}"}
          ]
          EOF
          echo "rabbitmq-versions=$(cat versions.json | jq -c .)" >> $GITHUB_OUTPUT

  build:
    needs: setup
    strategy:
      matrix:
        rabbitmq: ${{ fromJson(needs.setup.outputs.rabbitmq-versions) }}
        arch:
          - amd64
          - arm64
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build and push
        env:
          RABBITMQ_VER: ${{ matrix.rabbitmq.version }}
          ARCH: ${{ matrix.arch }}
        run: |
          make
          make test
          make push

  push:
    runs-on: ubuntu-latest
    needs:
      - setup
      - build
    strategy:
      matrix:
        rabbitmq: ${{ fromJson(needs.setup.outputs.rabbitmq-versions) }}
    steps:
      - uses: actions/checkout@v5
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: ./.github/actions
        with:
          version: ${{ matrix.rabbitmq.version }}
